"""
================================================================================
CASE STUDY -- MERIDIAN RETAIL
================================================================================

Meridian Retail pulls one day of orders from its Andheri store. Nine orders
came through, in thousands of rupees:

        12, 14, 15, 15, 18, 20, 22, 25, 99

Meridian also holds a treasury portfolio, and the finance team wants to know
how often a bad day happens. Their risk model assumes daily returns are
normally distributed. That assumption is about to fail, and kurtosis is the
statistic that detects the failure.

--------------------------------------------------------------------------------
THIS FILE: KURTOSIS
--------------------------------------------------------------------------------

Kurtosis measures the weight of the TAILS relative to a normal distribution.
It answers: how much of the total variance is being generated by extreme
observations?

        raw kurtosis    : a normal distribution scores exactly 3
        excess kurtosis : raw minus 3, so a normal distribution scores 0

Almost every software package reports EXCESS kurtosis. Check before you
interpret. pandas .kurt() and scipy.stats.kurtosis() both return excess.

Sections:
        1. Kurtosis from scratch -- and why the formula raises to the fourth
        2. The three tail regimes
        3. Why it is a risk metric -- how often a normal model says "never"
        4. The peakedness misreading
        5. The full diagnostic workflow across all five statistics
================================================================================
"""

import math
import numpy as np
import pandas as pd


ORDER_VALUES = [12, 14, 15, 15, 18, 20, 22, 25, 99]
ORDER_VALUES_NO_BULK = [12, 14, 15, 15, 18, 20, 22, 25]

orders = pd.Series(ORDER_VALUES, dtype=float)


# ==============================================================================
# SECTION 1 -- KURTOSIS FROM SCRATCH
# ==============================================================================

def excess_kurtosis_population(values):
    """
    The straightforward population version of excess kurtosis.

            raw    = mean of ((x - mean) / sigma) ^ 4
            excess = raw - 3

    where sigma is the POPULATION standard deviation (divide by n).

    Why the FOURTH power:
        - It removes the sign completely. A deviation of -3 and a deviation of
          +3 both contribute 81. Kurtosis is direction-blind by design -- it
          reads both tails together. Skewness is the statistic for direction.
        - It amplifies distance even harder than the cube in skewness. A value
          4 standard deviations out contributes 256 units; a value half a
          standard deviation out contributes 0.0625.
        - So the statistic is driven almost entirely by the far observations.
          Values near the centre are effectively invisible to it.

    Why subtract 3: the normal distribution has a raw kurtosis of exactly 3,
    so subtracting it makes "normal" the zero point and turns the statistic
    into a comparison rather than an absolute quantity.
    """
    n = len(values)

    if n < 4:
        raise ValueError("kurtosis needs at least 4 observations to be meaningful")

    mean = sum(values) / n

    # Population standard deviation -- divide by n, not n-1.
    variance = sum((v - mean) ** 2 for v in values) / n
    sd = math.sqrt(variance)

    if sd == 0:
        return 0.0

    # Average of the standardised deviations raised to the fourth power.
    raw = sum(((v - mean) / sd) ** 4 for v in values) / n

    return raw - 3.0


def excess_kurtosis_sample(values):
    """
    The sample-adjusted version, which is what pandas .kurt() returns.

    The correction factors below do the same job as n-1 in the variance:
    they remove a bias that appears when estimating a population quantity
    from a small sample. On large samples the two versions converge.

    You will rarely type this formula out. It is here so the number pandas
    gives you is not a black box.
    """
    n = len(values)

    if n < 4:
        raise ValueError("sample kurtosis needs at least 4 observations")

    mean = sum(values) / n
    # Note: sample standard deviation here, dividing by n-1.
    sd = math.sqrt(sum((v - mean) ** 2 for v in values) / (n - 1))

    if sd == 0:
        return 0.0

    fourth_power_sum = sum(((v - mean) / sd) ** 4 for v in values)

    # Two correction terms, applied to the sum and then subtracted.
    first_term = (n * (n + 1)) / ((n - 1) * (n - 2) * (n - 3)) * fourth_power_sum
    second_term = (3 * (n - 1) ** 2) / ((n - 2) * (n - 3))

    return first_term - second_term


def show_kurtosis_contributions(values, label):
    """
    Show how much each observation contributes to the kurtosis total.

    This is the most direct way to see what kurtosis actually measures. The
    share column collapses almost entirely onto the extreme observations,
    which is the whole point of the fourth power.
    """
    n = len(values)
    mean = sum(values) / n
    sd = math.sqrt(sum((v - mean) ** 2 for v in values) / n)

    print(f"\n{label}")
    print(f"  mean = {mean:.2f}, sigma = {sd:.2f}\n")
    print(f"  {'value':>8} {'z':>10} {'z^4':>14} {'share of total':>16}")
    print("  " + "-" * 52)

    fourth_powers = [((v - mean) / sd) ** 4 for v in values]
    total = sum(fourth_powers)

    for v, p in zip(values, fourth_powers):
        z = (v - mean) / sd
        print(f"  {v:>8.0f} {z:>+10.3f} {p:>14.3f} {p / total * 100:>15.1f}%")

    print("  " + "-" * 52)
    print(f"  {'SUM':>8} {'':>10} {total:>14.3f}")
    print(f"\n  raw kurtosis    = {total / n:.3f}")
    print(f"  excess kurtosis = {total / n - 3:.3f}")


# ==============================================================================
# SECTION 2 -- THE THREE TAIL REGIMES
# ==============================================================================

def classify_kurtosis(excess):
    """
    Name the tail regime from an excess kurtosis value.

        LEPTOKURTIC   excess > 0   fat tails, extremes more common than normal
        MESOKURTIC    excess ~ 0   normal-like tails
        PLATYKURTIC   excess < 0   thin tails, extremes rarer than normal
    """
    if excess > 1.0:
        return "LEPTOKURTIC", "fat tails -- extreme values more common than a normal model expects"
    elif excess < -1.0:
        return "PLATYKURTIC", "thin tails -- extreme values rarer than a normal model expects"
    else:
        return "MESOKURTIC", "tails roughly like a normal distribution"


def build_tail_examples(seed=7):
    """
    Generate three distributions with the same mean and standard deviation
    but different tail weight.

    Holding mean and standard deviation constant is the important part. It
    proves kurtosis is measuring something the first three statistics cannot
    see.
    """
    rng = np.random.default_rng(seed)
    size = 20_000

    # MESOKURTIC: a normal distribution. Excess kurtosis near 0.
    normal = pd.Series(rng.normal(loc=0, scale=1, size=size))

    # LEPTOKURTIC: Student's t with low degrees of freedom. Same general shape
    # as a normal but with much heavier tails. This is the standard model for
    # financial returns precisely because real returns have fat tails.
    heavy = pd.Series(rng.standard_t(df=4, size=size))

    # PLATYKURTIC: a uniform distribution. Hard boundaries, so no tails at all.
    thin = pd.Series(rng.uniform(low=-1, high=1, size=size))

    # Standardise all three to mean 0 and standard deviation 1, so the only
    # remaining difference between them is shape.
    normal = (normal - normal.mean()) / normal.std()
    heavy = (heavy - heavy.mean()) / heavy.std()
    thin = (thin - thin.mean()) / thin.std()

    return {"normal (mesokurtic)": normal,
            "Student t, df=4 (leptokurtic)": heavy,
            "uniform (platykurtic)": thin}


# ==============================================================================
# SECTION 3 -- WHY KURTOSIS IS A RISK METRIC
# ==============================================================================

def count_extreme_observations(series, thresholds=(2, 3, 4, 5)):
    """
    Count how many observations sit beyond a given number of standard
    deviations, and compare that to what a normal distribution predicts.

    This converts an abstract kurtosis value into a business quantity:
    how often does the bad day actually happen, versus how often the model
    said it would?
    """
    # Standardise so thresholds are in standard deviation units.
    z = (series - series.mean()) / series.std()

    # Probabilities a normal distribution assigns to being beyond k sigma,
    # in either direction. These are the textbook values.
    normal_probability = {2: 0.0455, 3: 0.0027, 4: 0.0000633, 5: 0.00000057}

    results = []
    for k in thresholds:
        # .abs() makes both tails count. .sum() on a True/False Series counts
        # the True values, because True behaves as 1 in arithmetic.
        observed_count = (z.abs() > k).sum()
        observed_rate = observed_count / len(series)
        expected_rate = normal_probability[k]

        results.append({
            "threshold": f"beyond {k} sigma",
            "observed": observed_count,
            "observed_rate": observed_rate,
            "expected_rate": expected_rate,
            # How many times more often than the normal model predicted.
            "ratio": observed_rate / expected_rate if expected_rate > 0 else float("nan"),
        })

    return results


def show_risk_case(seed=7):
    """
    Meridian's treasury portfolio: 10 years of daily returns.

    The risk model assumes normality. We generate returns with genuinely
    fat tails and then ask the normal model how often a 4-sigma day should
    happen, versus how often it did.
    """
    rng = np.random.default_rng(seed)

    # Roughly 10 years of trading days.
    days = 2520

    # Fat-tailed daily returns, scaled to about 1% daily volatility.
    returns = pd.Series(rng.standard_t(df=3, size=days) * 0.01)

    print(f"\n  {days} daily returns")
    print(f"    mean            : {returns.mean() * 100:8.4f}%")
    print(f"    std deviation   : {returns.std() * 100:8.4f}%")
    print(f"    skewness        : {returns.skew():8.2f}")
    print(f"    excess kurtosis : {returns.kurt():8.2f}")

    regime, meaning = classify_kurtosis(returns.kurt())
    print(f"    -> {regime}: {meaning}")

    print(f"\n  {'threshold':<18} {'observed':>10} {'observed %':>12} "
          f"{'normal model %':>16} {'times worse':>13}")
    print("  " + "-" * 74)

    for row in count_extreme_observations(returns):
        print(f"  {row['threshold']:<18} {row['observed']:>10} "
              f"{row['observed_rate'] * 100:>11.3f}% "
              f"{row['expected_rate'] * 100:>15.4f}% "
              f"{row['ratio']:>12.1f}x")

    print("\n  A normal model would call the 4-sigma days a once-in-60-years")
    print("  event. Here they turn up repeatedly in a decade. That gap between")
    print("  assumed and actual tail weight is what kurtosis is measuring, and")
    print("  it is a large part of what went wrong with risk models in 2008.")


# ==============================================================================
# SECTION 4 -- THE PEAKEDNESS MISREADING
# ==============================================================================

def show_peakedness_myth():
    """
    Demonstrate that kurtosis is about tails, not about the height of the peak.

    The common textbook error is "high kurtosis means a tall sharp peak".
    It does not. The fourth power gives observations near the centre almost
    no weight at all, so the centre barely participates in the calculation.

    We prove it by taking a normal distribution and moving observations
    outward into the tails while leaving the centre alone.
    """
    rng = np.random.default_rng(99)

    base = pd.Series(rng.normal(0, 1, 10_000))
    base = (base - base.mean()) / base.std()

    # Copy the data and push a small number of observations far out into the
    # tails. The bulk of the distribution -- the middle -- is untouched.
    fattened = base.copy()
    # Pick 40 positions at random and multiply those values by 5.
    positions = rng.choice(len(fattened), size=40, replace=False)
    fattened.iloc[positions] = fattened.iloc[positions] * 5

    # Re-standardise so both series still have mean 0 and standard deviation 1.
    fattened = (fattened - fattened.mean()) / fattened.std()

    # Count observations near the centre in each version.
    centre_base = ((base.abs() < 0.5).sum() / len(base)) * 100
    centre_fat = ((fattened.abs() < 0.5).sum() / len(fattened)) * 100

    print(f"\n  {'':<26} {'original':>12} {'tails fattened':>16}")
    print("  " + "-" * 56)
    print(f"  {'excess kurtosis':<26} {base.kurt():>12.2f} {fattened.kurt():>16.2f}")
    print(f"  {'% within 0.5 sigma':<26} {centre_base:>11.1f}% {centre_fat:>15.1f}%")
    print(f"  {'% beyond 3 sigma':<26} "
          f"{(base.abs() > 3).sum() / len(base) * 100:>11.2f}% "
          f"{(fattened.abs() > 3).sum() / len(fattened) * 100:>15.2f}%")

    print("\n  We changed 40 observations out of 10,000, all of them far from")
    print("  the centre. Kurtosis moved sharply. The proportion of data near")
    print("  the middle barely changed.")
    print("\n  Read kurtosis as: how much of the variance is being generated by")
    print("  extreme observations. Not as: how tall is the peak.")


# ==============================================================================
# SECTION 5 -- THE FULL DIAGNOSTIC
# ==============================================================================

def full_diagnostic(series, label):
    """
    Run every statistic from this course in the order you should run them,
    and print the decision each one leads to.

    This is the function to reuse on real data.
    """
    n = len(series)
    mean = series.mean()
    median = series.median()
    sd = series.std()
    q1, q3 = series.quantile(0.25), series.quantile(0.75)
    iqr = q3 - q1
    skew = series.skew()
    kurt = series.kurt()

    print(f"\n{'=' * 74}")
    print(f"DIAGNOSTIC: {label}")
    print(f"{'=' * 74}")

    print(f"\n  STEP 1 -- size and centre")
    print(f"    n      = {n}")
    print(f"    mean   = {mean:.2f}")
    print(f"    median = {median:.2f}")

    gap_pct = (mean - median) / median * 100 if median != 0 else 0
    print(f"    the mean sits {gap_pct:+.1f}% from the median")

    print(f"\n  STEP 2 -- spread")
    print(f"    std deviation = {sd:.2f}")
    print(f"    IQR           = {iqr:.2f}")
    print(f"    CV            = {sd / mean:.2f}" if mean != 0 else "    CV: not meaningful")

    print(f"\n  STEP 3 -- symmetry")
    print(f"    skewness = {skew:+.2f}")
    if abs(skew) > 1:
        print(f"    -> highly skewed. Report the MEDIAN as the headline number.")
    elif abs(skew) > 0.5:
        print(f"    -> moderately skewed. Report the median alongside the mean.")
    else:
        print(f"    -> roughly symmetric. The mean is safe.")

    print(f"\n  STEP 4 -- tails")
    print(f"    excess kurtosis = {kurt:+.2f}")
    regime, meaning = classify_kurtosis(kurt)
    print(f"    -> {regime}: {meaning}")

    print(f"\n  STEP 5 -- flag extremes with the IQR fence")
    lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    flagged = series[(series < lower) | (series > upper)]
    print(f"    fence: [{lower:.2f}, {upper:.2f}]")
    if len(flagged):
        print(f"    flagged: {sorted(flagged.tolist())[:10]}"
              f"{' ...' if len(flagged) > 10 else ''}  ({len(flagged)} total)")
        print(f"    -> go and look at these before deciding anything.")
    else:
        print(f"    nothing flagged")


# ==============================================================================
# SECTION 6 -- RUN EVERYTHING
# ==============================================================================

if __name__ == "__main__":

    print("=" * 78)
    print("KURTOSIS -- MERIDIAN RETAIL")
    print("=" * 78)

    # --- Section 1 -----------------------------------------------------------
    print("\n" + "-" * 78)
    print("1. KURTOSIS FROM SCRATCH")
    print("-" * 78)

    show_kurtosis_contributions(ORDER_VALUES, "ALL NINE ORDERS")

    # Verify the sample version against pandas.
    ours = excess_kurtosis_sample(ORDER_VALUES)
    theirs = orders.kurt()
    assert abs(ours - theirs) < 1e-9
    print(f"\n  our sample formula agrees with pandas .kurt(): {theirs:.4f}")
    print(f"  the simpler population formula gives         : "
          f"{excess_kurtosis_population(ORDER_VALUES):.4f}")
    print("\n  The two differ on small samples and converge as n grows. Always")
    print("  check which version your tool reports before you interpret it.")

    print(f"\n  bulk order removed: excess kurtosis = "
          f"{excess_kurtosis_sample(ORDER_VALUES_NO_BULK):+.2f}")
    print(f"  all nine orders   : excess kurtosis = {theirs:+.2f}")
    print("  One observation swung the tail metric by more than nine units.")

    # --- Section 2 -----------------------------------------------------------
    print("\n" + "-" * 78)
    print("2. THE THREE TAIL REGIMES")
    print("-" * 78)

    print("\n  All three standardised to mean 0 and std deviation 1, so the only")
    print("  difference between them is the shape of the tails.\n")
    print(f"  {'distribution':<32} {'mean':>7} {'std':>7} {'skew':>8} {'excess kurt':>13}")
    print("  " + "-" * 72)

    for name, series in build_tail_examples().items():
        print(f"  {name:<32} {series.mean():>7.2f} {series.std():>7.2f} "
              f"{series.skew():>8.2f} {series.kurt():>13.2f}")

    print("\n  Identical mean. Identical standard deviation. Near-zero skewness")
    print("  in all three. Only kurtosis distinguishes them -- which is the")
    print("  argument for computing it at all.")

    # --- Section 3 -----------------------------------------------------------
    print("\n" + "-" * 78)
    print("3. WHY KURTOSIS IS A RISK METRIC")
    print("-" * 78)

    show_risk_case()

    print("""
  Where fat tails matter commercially:
    financial returns  -- normal-tail models underprice large drawdowns
    fraud detection    -- a heavy tail in transaction amounts is a lead
    operational risk   -- staff against the tail recovery time, not the mean
    data quality       -- extreme kurtosis in a well-behaved field usually
                          means unit errors, duplicates, or a sentinel like 999
    """)

    # --- Section 4 -----------------------------------------------------------
    print("-" * 78)
    print("4. THE PEAKEDNESS MISREADING")
    print("-" * 78)

    show_peakedness_myth()

    # --- Section 5 -----------------------------------------------------------
    print("\n" + "-" * 78)
    print("5. THE FULL DIAGNOSTIC, END TO END")
    print("-" * 78)

    full_diagnostic(orders, "MERIDIAN ORDERS -- ALL NINE")
    full_diagnostic(pd.Series(ORDER_VALUES_NO_BULK, dtype=float),
                    "MERIDIAN ORDERS -- BULK ORDER REMOVED")

    # --- Closing -------------------------------------------------------------
    print("\n" + "=" * 78)
    print("THE WORKFLOW FOR ANY NEW NUMERIC COLUMN")
    print("=" * 78)
    print("""
  1. Plot the histogram. Two peaks means two populations -- segment and stop.
  2. Compare mean and median. The gap gives you the shape for free.
  3. Compute standard deviation and IQR. A large s relative to the mean
     means expect a tail.
  4. Compute skewness. Beyond +/- 1, switch your headline to the median.
  5. Compute kurtosis. Above +3 excess, treat the tail as a business risk
     rather than a data error.
  6. Apply the IQR fence. Flag, investigate, then decide. Never delete first.

  COMMON PITFALLS
    - averaging categorical codes such as pin codes or product IDs
    - reporting a mean on skewed data with no median beside it
    - using z-scores for outlier detection on skewed data (file 04)
    - confusing raw kurtosis with excess kurtosis
    - summarising a bimodal column at all (file 03)

  ONE LINE TO REMEMBER
    Never report a centre without a spread, and never report either without
    checking the shape.
    """)
